[mypy]
python_version = 3.9
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = False

# Ignore missing imports for foundry SDK
[mypy-foundry.*]
ignore_missing_imports = True

# pyarrow ships no py.typed marker
[mypy-pyarrow.*]
ignore_missing_imports = True
